[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_USE_NODE_IMG = "true"
  ROLLUP_SKIP_NATIVE_BUILD_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200